name: crave_food
description: A Flutter app with Firebase authentication

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  
  # State management
  provider: ^6.1.1
  
  # UI components
  cupertino_icons: ^1.0.8
  
  # Form validation
  email_validator: ^2.1.17
  
  # Loading indicators
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true