name: crave_food
description: A Flutter app with Firebase authentication

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies (updated versions)
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  
  # State management
  provider: ^6.1.1
  
  # UI components
  cupertino_icons: ^1.0.8
  
  # Form validation
  email_validator: ^2.1.17
  
  # Loading indicators
  flutter_spinkit: ^5.2.0
  
  # URL handling
  url_launcher: ^6.2.1
  
  # HTTP requests
  http: ^1.1.0
  
  # Environment variables
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Include environment file
  assets:
    - .env