// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-9GRIoTwKTvvcJf5pIAQMh0h3u3PUlEg',
    appId: '1:173757499776:web:985e4b1151a1336ab1d965',
    messagingSenderId: '173757499776',
    projectId: 'crave-food-dev-060625',
    authDomain: 'crave-food-dev-060625.firebaseapp.com',
    storageBucket: 'crave-food-dev-060625.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCke-7Rbt1xuahYeXftvOnT5tjE8vp70Eg',
    appId: '1:173757499776:android:f54347e4111c8072b1d965',
    messagingSenderId: '173757499776',
    projectId: 'crave-food-dev-060625',
    storageBucket: 'crave-food-dev-060625.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdA5biAI6vQM03km3C5cQ0C5WyI73lBjs',
    appId: '1:173757499776:ios:d414dadf693f3a26b1d965',
    messagingSenderId: '173757499776',
    projectId: 'crave-food-dev-060625',
    storageBucket: 'crave-food-dev-060625.firebasestorage.app',
    iosBundleId: 'com.example.craveFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdA5biAI6vQM03km3C5cQ0C5WyI73lBjs',
    appId: '1:173757499776:ios:d414dadf693f3a26b1d965',
    messagingSenderId: '173757499776',
    projectId: 'crave-food-dev-060625',
    storageBucket: 'crave-food-dev-060625.firebasestorage.app',
    iosBundleId: 'com.example.craveFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-9GRIoTwKTvvcJf5pIAQMh0h3u3PUlEg',
    appId: '1:173757499776:web:39f5215add208643b1d965',
    messagingSenderId: '173757499776',
    projectId: 'crave-food-dev-060625',
    authDomain: 'crave-food-dev-060625.firebaseapp.com',
    storageBucket: 'crave-food-dev-060625.firebasestorage.app',
  );
}
